### ISSUE TITLE
Upload error with new conda_build version (2.0.11)

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#105]
As #104 passed the tests on both travis and appveyor, I've merged it a few days ago. However during upload both CI failed with the following error below. There was a change in the version of ``conda_build`` from 2.0.10 to 2.0.11 since the last successful merge, I couldn't spot another difference.

https://ci.appveyor.com/project/Astropy/conda-channel-astropy/build/1.0.335/job/20k7rdbave77no93
https://travis-ci.org/astropy/conda-channel-astropy/jobs/181110463

```
TEST END: pydl-0.5.3-py27_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload C:\Miniconda3-x64\conda-bld\win-64\pydl-0.5.3-py27_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
Traceback (most recent call last):
  File "C:\Miniconda3-x64\Scripts\conda-build-all-script.py", line 11, in <module>
    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
  File "C:\Miniconda3-x64\lib\site-packages\conda_build_all\cli.py", line 90, in main
    b.main()
  File "C:\Miniconda3-x64\lib\site-packages\conda_build_all\builder.py", line 265, in main
    config=build_config)
  File "C:\Miniconda3-x64\lib\site-packages\conda_build_all\builder.py", line 285, in post_build
    config=config)
  File "C:\Miniconda3-x64\lib\site-packages\conda_build_all\artefact_destination.py", line 118, in make_available
    config=config)
  File "C:\Miniconda3-x64\lib\site-packages\conda_build_all\build.py", line 42, in upload
    fname = bldpkg_path(meta, config)
TypeError: bldpkg_path() takes 1 positional argument but 2 were given
Command exited with code 1
```

**Comment by mwcraig** [comment]
This is very odd, will take a look tonight at what changed in conda build.

**Comment by mwcraig** [comment]
Thanks for the fix though!

**Comment by mwcraig** [comment]
Writing some notes here, won't get to a fix tonight (and not sure what the time scale for a fix getting merged will be):

+ `conda-build-all` calls conda build's `bldpkg_path` to find the built file for upload.
+ `bldpkg_path` is not part of the public API in conda build 2, and its signature changed from 2.0.9 to 2.0.10.
+ The API function for getting that information is `get_output_file_path`

**Comment by lbdreyer** [comment]
A new version of conda-build-all which included https://github.com/SciTools/conda-build-all/pull/68 was released yesterday but unfortunately this hasn't fixed the compatibility with the latest versions of  conda-build 2:
```
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-build-all", line 11, in <module>
    load_entry_point('conda-build-all==1.0.1', 'console_scripts', 'conda-build-all')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build_all/cli.py", line 90, in main
    b.main()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build_all/builder.py", line 269, in main
    config=build_config)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build_all/builder.py", line 289, in post_build
    config=config)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build_all/artefact_destination.py", line 118, in make_available
    config=config)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build_all/build.py", line 43, in upload
    fname = bldpkg_path(meta, config)
TypeError: bldpkg_path() takes 1 positional argument but 2 were given
```

see @ocefpaf 's [comment ](https://github.com/SciTools/conda-build-all/pull/68#discussion_r93306331)

**Comment by mwcraig** [comment]
This has been fixed for a while, closing....
