### ISSUE TITLE
Uoload machinery is broken

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#134]
This is something new, @mwcraig you may have a better idea which recent change is causing the error
https://travis-ci.org/astropy/conda-channel-astropy/jobs/202399380#L2159

```
Fetching package metadata .....

Uploading regions to the main channel.

INFO artefact_destination:make_available(116): Uploading regions to the main channel.

Traceback (most recent call last):

  File "/home/travis/miniconda/bin/conda-build-all", line 6, in <module>

    sys.exit(conda_build_all.cli.main())

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/cli.py", line 90, in main

    b.main()

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/builder.py", line 269, in main

    config=build_config)

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/builder.py", line 289, in post_build

    config=config)

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/artefact_destination.py", line 118, in make_available

    config=config)

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build_all/build.py", line 43, in upload

    fname = bldpkg_path(meta, config)

TypeError: bldpkg_path() takes exactly 1 argument (2 given)
```

(The PR passed the tests as we don't test the upload part there...)

**Comment by mwcraig** [comment]
this is now fixed.

**Comment by bsipocz** [comment]
Thanks @mwcraig!
